From file
AlexeyNikitin01/sparse_matrix pull request #3
Opened 2021-10-13 04:44 UTC by AlexeyNikitin01

2021-10-14 08:00 UTC, AlexeyNikitin01 commented on sparse_matrix.py
> +    PATH_TO_FILE_TWO = 'MATRIX_TWO.txt'
а как показывать путь к файлам?

2021-10-14 08:03 UTC, just3mhz commented on sparse_matrix.py
> +    PATH_TO_FILE_TWO = 'MATRIX_TWO.txt'
Класс SparseMatrix ничего не должен знать о файлах. 
Файлы используются только в методе from_file

2021-10-14 09:59 UTC, just3mhz requested changes

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +        self.size_mat_row = size_mat_row
n_cols и n_rows

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +        return
Этот метод тоже пока не нужен

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +            _rows_pointers = [0, ]
Здесь нижние подчеркивания не нужны

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +            size_mat_row = 0
Считай эти значения из файла

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +            size_mat_row += max(_cols)+1
И как это вообще должно работать?

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +                for count, val_in_line in enumerate(row):
Напиши здесь более классический цикл:
```
for col in range(n_cols):
     if row[col]:
          ...
```

2021-10-14 09:59 UTC, just3mhz commented on sparse_matrix.py
> +        self.size_mat_row = size_mat_row
Нужно написать комментарии или ссылку на алгоритм

2021-10-14 19:58 UTC, AlexeyNikitin01 commented on sparse_matrix.py
> +            size_mat_row = 0
Не понятно как их из файла считывать, если мы тип пробегаемся по строчно.

2021-10-14 19:59 UTC, AlexeyNikitin01 commented on sparse_matrix.py
> +                for count, val_in_line in enumerate(row):
Просто там сразу значение колонки есть и ненулевой элемент, удобно.

2021-10-16 10:47 UTC, just3mhz requested changes

2021-10-16 10:47 UTC, just3mhz commented on test_sparse_matrix.py
> +        from_file = check.from_file('MATRIX.txt')
Название переменной поменяй

2021-10-16 10:47 UTC, just3mhz commented on sparse_matrix.py
> +            for line in f:
```
for _ in range(n_rows):
     row = [int(x) for x in f.readline().strip().split()]
     ...
```

2021-10-16 10:47 UTC, just3mhz commented on sparse_matrix.py
> +                    if row[col]:
```row[col] != 0```

2021-10-16 10:47 UTC, just3mhz commented on test_sparse_matrix.py
> +        check = SparseMatrix
Мусор

2021-10-16 10:47 UTC, just3mhz commented on test_sparse_matrix.py
> +        from_file = check.from_file('MATRIX.txt')
Например ```sparse_matrix```

2021-10-16 10:47 UTC, just3mhz commented on sparse_matrix.py
> +        self._val = val
```_vals```

2021-11-05 11:41 UTC, merged